language: rust

script:
- cargo build
- cargo test

after_success: |
  sudo apt-get install libcurl4-openssl-dev libelf-dev libdw-dev &&
  wget https://github.com/SimonKagstrom/kcov/archive/master.tar.gz &&
  tar xzf master.tar.gz &&
  mkdir kcov-master/build &&
  cd kcov-master/build &&
  cmake .. &&
  make &&
  sudo make install &&
  cd ../.. &&
  kcov --coveralls-id=$TRAVIS_JOB_ID --exclude-pattern=/.cargo target/kcov target/debug/rust_coverage_sample-*;
  cargo clean;
  cargo build --release;
  fpm -s dir -t deb -C target/release --name maidsafe_sample --version 0.0.1 --iteration 1 --maintainer qa@maidsafe.net --prefix /tmp/ross3 --description "Very simple example";
